<!DOCTYPE html>
<html lang="id" class="h-full bg-slate-50">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, viewport-fit=cover">
    <meta name="theme-color" content="#15803D">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title', 'Sistem Absensi MA Ma\'arif Cilageni')</title>

    <!-- Favicon -->
    <link rel="icon" type="image/png" href="{{ asset('img/d41a7486-229a-4c8a-9dc7-549fa8b467b0.png') }}">
    <link rel="apple-touch-icon" href="{{ asset('img/d41a7486-229a-4c8a-9dc7-549fa8b467b0.png') }}">

    <link rel="manifest" href="/manifest.json">

    {{-- Critical above-the-fold: Vite injects CSS synchronously, JS with defer --}}
    @vite(['resources/css/app.css', 'resources/js/app.js'])

    {{-- LCP hint: tell browser to fetch the logo early (rendered in sidebar/header) --}}
    <link rel="preload" as="image" href="{{ asset('img/d41a7486-229a-4c8a-9dc7-549fa8b467b0.png') }}" fetchpriority="high">
    {{-- Bunny self-hosted fonts (generated by laravel-vite-plugin/fonts, must be loaded explicitly) --}}
    @php
        $fontsFile = null;
        // Primary: fonts-manifest.json (source of truth for bunny)
        $fontsManifestPath = public_path('build/fonts-manifest.json');
        if (file_exists($fontsManifestPath)) {
            $fm = @json_decode(@file_get_contents($fontsManifestPath), true);
            $fontsFile = $fm['style']['file'] ?? null;
        }
        // Fallback: scan build/manifest.json for _fonts*.css
        if (!$fontsFile) {
            $manifest = @json_decode(@file_get_contents(public_path('build/manifest.json')), true);
            if (is_array($manifest)) {
                foreach ($manifest as $key => $meta) {
                    if (str_starts_with($key, '_fonts') && str_ends_with($key, '.css')) {
                        $fontsFile = $meta['file'] ?? null;
                        break;
                    }
                }
            }
        }
    @endphp
    @if($fontsFile)
        <link rel="stylesheet" href="{{ asset('build/' . $fontsFile) }}">
    @endif
    <noscript>
        <style>
            [x-cloak] { display: block !important; }
            [x-show*="!ready"], [x-show*="!shown"] { display: none !important; }
        </style>
    </noscript>
    <script>
        window.__serverTimeMs = {{ \Carbon\Carbon::now()->getTimestampMs() }};
        window.__clientInitMs = Date.now();
        window.getServerNow = function() {
            return new Date(window.__serverTimeMs + (Date.now() - window.__clientInitMs));
        };
    </script>
    <style>
        .heading-font {
            font-family: 'Inter', ui-sans-serif, system-ui, sans-serif;
        }
        .mono-font {
            font-family: 'JetBrains Mono', monospace;
        }
        .safe-bottom {
            padding-bottom: max(env(safe-area-inset-bottom, 0px), 8px);
        }
        .touch-btn {
            min-height: 48px;
            min-width: 48px;
        }
    </style>

    <div id="page-styles-container" class="contents">
        @stack('styles')
    </div>
</head>
<body class="min-h-full bg-slate-50 text-slate-900 flex flex-col antialiased selection:bg-maarif-100 selection:text-maarif-800">
    <!-- Main Application Container (Full Width Responsive) -->
    <!-- Main Application Wrapper -->
    <div class="w-full min-h-screen bg-slate-50 flex flex-col md:flex-row relative">
        
        <!-- 1. MODULAR UNIFIED DESKTOP SIDEBAR (Visible on screens >= 768px) -->
        @include('partials.sidebar')

        <!-- Right Content Area Wrapper -->
        <div class="flex-1 flex flex-col min-w-0 min-h-screen bg-slate-50">

            <!-- 1. DESKTOP TOP HEADER BAR (Synchronized h-[72px] with Sidebar Brand & Crisp Elevated Bottom Shadow) -->
            <header class="hidden md:flex sticky top-0 z-20 h-[72px] px-6 sm:px-8 bg-emerald-800 border-b border-emerald-900/20 items-center justify-between text-white shrink-0" style="height: 72px; min-height: 72px;">
                <!-- Left: Page Title with Category Hierarchy -->
                <div id="desktop-header-title" class="flex flex-col justify-center">
                    <span class="text-[11px] font-semibold uppercase tracking-widest text-emerald-200/90 leading-none mb-1">
                        @if(Auth::check() && Auth::user()->role === 'guru')
                            Portal Dewan Guru
                        @elseif(Auth::check() && Auth::user()->role === 'siswa')
                            Portal Siswa
                        @elseif(Auth::check() && Auth::user()->role === 'admin')
                            Panel Administrator
                        @else
                            Sistem Presensi
                        @endif
                    </span>
                    <h2 class="text-base sm:text-lg font-semibold text-white heading-font tracking-tight leading-none">
                        @hasSection('page-title')
                            @yield('page-title')
                        @elseif(\Illuminate\Support\Facades\View::hasSection('title'))
                            @php
                                $cleanTitle = trim(explode('—', \Illuminate\Support\Facades\View::yieldContent('title'))[0]);
                            @endphp
                            {{ $cleanTitle }}
                        @else
                            @if(request()->routeIs('siswa.dashboard'))
                                Dashboard
                            @elseif(request()->routeIs('siswa.schedule'))
                                Jadwal Pelajaran
                            @elseif(request()->routeIs('siswa.history'))
                                Riwayat Presensi
                            @elseif(request()->routeIs('siswa.leaves.*'))
                                Pengajuan Izin
                            @elseif(request()->routeIs('profile*'))
                                Profil Pengguna
                            @elseif(request()->routeIs('guru.dashboard'))
                                Dashboard
                            @elseif(request()->routeIs('guru.scan'))
                                Pindai QR Presensi
                            @elseif(request()->routeIs('guru.session'))
                                Presensi Kelas
                            @elseif(request()->routeIs('guru.reconcile'))
                                Konfirmasi Keterangan Siswa
                            @elseif(request()->routeIs('guru.history'))
                                Riwayat Kelas Mengajar
                            @else
                                Dashboard
                            @endif
                        @endif
                    </h2>
                </div>
            </header>

            <!-- 2. MOBILE TOP BAR (Visible only on screens < 768px) -->
            <header class="md:hidden sticky top-0 z-40 h-16 px-4 bg-gradient-to-r from-emerald-800 via-maarif-700 to-emerald-800 border-b border-emerald-900/80 flex items-center justify-between text-white">
                <div class="flex items-center space-x-3">
                    <img src="{{ asset('img/d41a7486-229a-4c8a-9dc7-549fa8b467b0.png') }}" alt="Logo MA Ma'arif Cilageni" class="w-11 h-11 object-contain shrink-0 drop-shadow-md" width="44" height="44" fetchpriority="high">
                    <div id="mobile-header-title">
                        <h1 class="text-[10px] font-semibold tracking-wider text-emerald-200 uppercase">MA Ma'arif Cilageni</h1>
                        <p class="text-sm font-semibold text-white heading-font leading-tight">
                            @hasSection('page-title')
                                @yield('page-title')
                            @elseif(\Illuminate\Support\Facades\View::hasSection('title'))
                                @php
                                    $cleanMobileTitle = trim(explode('—', \Illuminate\Support\Facades\View::yieldContent('title'))[0]);
                                @endphp
                                {{ $cleanMobileTitle }}
                            @else
                                Dashboard
                            @endif
                        </p>
                    </div>
                </div>
                <div class="flex items-center space-x-2">
                    @auth
                        <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-semibold {{ Auth::user()->role === 'guru' ? 'bg-amber-300 text-slate-900 border border-amber-400 shadow-2xs' : 'bg-emerald-600 text-white border border-emerald-500 shadow-2xs' }}">
                            {{ strtoupper(Auth::user()->role) }}
                        </span>
                        <form action="{{ route('logout') }}" method="POST" class="inline"
                            data-confirm="Apakah Anda yakin ingin mengakhiri sesi dan keluar dari sistem absensi?"
                            data-confirm-title="Konfirmasi Keluar"
                            data-confirm-type="warning"
                            data-confirm-btn="Ya, Keluar"
                            data-confirm-icon="log-out">
                            @csrf
                            <button type="submit" title="Keluar dari sistem" aria-label="Keluar dari sistem" class="p-1.5 rounded-lg text-emerald-100 hover:text-white hover:bg-rose-600/80 transition-all duration-150 active:scale-95 cursor-pointer focus:outline-none focus-visible:ring-2 focus-visible:ring-white">
                                <i data-lucide="log-out" class="w-5 h-5"></i>
                            </button>
                        </form>
                    @endauth
                </div>
            </header>



            <!-- 3. MAIN CONTENT (Generous top padding/margin for comfortable spacing below elevated header) -->
            <main id="main-content" class="flex-1 w-full px-4 sm:px-6 lg:px-8 pt-6 sm:pt-8 md:pt-8 pb-36 md:pb-12">
                @yield('content')
            </main>
        </div>

        <!-- 4. MOBILE BOTTOM NAVIGATION BAR (Strictly hidden on md: and above) -->
        @include('partials.bottom-nav')
    </div>

    <!-- Haptic feedback and service worker registration -->
    <script>
        window.triggerHaptic = function(pattern = [50]) {
            if (navigator.vibrate) {
                try {
                    navigator.vibrate(pattern);
                } catch(e) {}
            }
        };

        if ('serviceWorker' in navigator) {
            window.addEventListener('load', () => {
                navigator.serviceWorker.register('/service-worker.js').catch(() => {});
            });
        }
    </script>
    @if(app()->environment('local'))
        @include('partials.time-simulator')
    @endif
    @include('partials.confirm-dialog')
    @include('partials.toast-notification')
    @include('partials.partial-nav')

    <!-- Persistent Flash Messages Bridge for SPA Navigation -->
    <div id="page-flash-messages" class="hidden"
         data-success="{{ session('success') ?? '' }}"
         data-error="{{ session('error') ?? ($errors->any() ? $errors->first() : '') }}"
         data-warning="{{ session('warning') ?? '' }}"
         data-info="{{ session('info') ?? '' }}"></div>

    <div id="page-scripts-container" class="contents">
        @stack('scripts')
    </div>
</body>
</html>
